ALTER TABLE `DeltaBD`.`AREA` 
ENGINE = InnoDB ;

ALTER TABLE `DeltaBD`.`DETAIL_PERT_PRODUCT` 
ENGINE = InnoDB ;

ALTER TABLE `DeltaBD`.`DIVISION` 
ENGINE = InnoDB ;

ALTER TABLE `DeltaBD`.`MEASURE_PRODUCT` 
ENGINE = InnoDB ;

ALTER TABLE `DeltaBD`.`PERTINENCES` 
ENGINE = InnoDB ;

ALTER TABLE `DeltaBD`.`PROCEDURE_TABLE` 
ENGINE = InnoDB ;

ALTER TABLE `DeltaBD`.`PROCESS` 
ENGINE = InnoDB ;

ALTER TABLE `DeltaBD`.`PRODUCT` 
ENGINE = InnoDB ;

ALTER TABLE `DeltaBD`.`ROL` 
ENGINE = InnoDB ;

ALTER TABLE `DeltaBD`.`USER` 
ENGINE = InnoDB ;


COMMIT