DROP PROCEDURE GET_USER_PU_RELATION_MEASURE_VIEW;
DELIMITER $$
CREATE PROCEDURE  GET_USER_PU_RELATION_MEASURE_VIEW
(
	IN dateFrom TIMESTAMP,
    IN dateTo	TIMESTAMP
)
BEGIN
	
   SELECT 
		MEASURE_PRODUCT.MSR_ID,
		USER.USR_PU,
		(SELECT COUNT(*) FROM MEASURE_PRODUCT WHERE MEASURE_PRODUCT.USR_ID = USER.USR_ID 
			AND MSR_DATE >= dateFrom AND MSR_DATE <= dateTo ) AS 'TOTAL_MEASURES'
        FROM MEASURE_PRODUCT
		LEFT JOIN USER ON USER.USR_ID = MEASURE_PRODUCT.USR_ID
        GROUP BY USER.USR_PU;

END $$

DROP PROCEDURE GET_ROL_RELATION_MEASURE_VIEW;
DELIMITER $$
CREATE PROCEDURE  GET_ROL_RELATION_MEASURE_VIEW
(
	IN dateFrom TIMESTAMP,
    IN dateTo	TIMESTAMP
)
BEGIN
	
   SELECT 
		MEASURE_PRODUCT.MSR_ID,
        ROL.ROL_NAME,
	   (SELECT COUNT(*) FROM MEASURE_PRODUCT WHERE MEASURE_PRODUCT.USR_ID = USER.USR_ID 
       AND MSR_DATE >= dateFrom AND MSR_DATE <= dateTo ) AS 'TOTAL_MEASURES'
       FROM MEASURE_PRODUCT
       LEFT JOIN USER ON USER.USR_ID = MEASURE_PRODUCT.USR_ID
       LEFT JOIN ROL ON ROL.ROL_ID = USER.ROL_ID
       GROUP BY USER.USR_PU;

END $$

CALL GET_EFECTIVITY_VIEW('2016-07-21 03:37:41', '2016-07-21 03:50:50');


DROP PROCEDURE GET_EFECTIVITY_VIEW;
DELIMITER $$
CREATE PROCEDURE GET_EFECTIVITY_VIEW
(
	IN dateFrom TIMESTAMP,
    IN dateTo	TIMESTAMP
) 
BEGIN
	
   SELECT * FROM EFECTIVITY_VIEW 
   WHERE DEFECTS > 0
		AND MSR_DATE >= dateFrom AND  MSR_DATE <= dateTo;

END $$


DROP PROCEDURE GET_EFECTIVITY_OK_VIEW;
DELIMITER $$
CREATE PROCEDURE GET_EFECTIVITY_OK_VIEW
(
	IN dateFrom TIMESTAMP,
    IN dateTo	TIMESTAMP
)
BEGIN
	
   SELECT * FROM EFECTIVITY_OK_VIEW
   WHERE MSR_DATE >= dateFrom AND  MSR_DATE <= dateTo;

END $$


DROP PROCEDURE GET_PRODUCT_NO_MEASURE_VIEW;
DELIMITER $$
CREATE PROCEDURE  GET_PRODUCT_NO_MEASURE_VIEW
(
)
BEGIN
	
   select 
		PRODUCT_VIEW.PDT_ID,
        PRODUCT_VIEW.PROC_N0_NAME, 
		PRODUCT_VIEW.PDT_NAME, 
		(CASE
        WHEN PRODUCT_VIEW.GOAL_QUANTITY_MONTH IS NULL THEN
            PRODUCT_VIEW.GOAL_SAMPLES
        ELSE
            PRODUCT_VIEW.GOAL_QUANTITY_MONTH
        END) as 'MEASURE_GOAL'
        
        from PRODUCT_VIEW
		left join MEASURE_VIEW 
		ON PRODUCT_VIEW.PDT_ID  = MEASURE_VIEW.PDT_ID
		WHERE MEASURE_VIEW.MSR_ID IS NULL
        ;


END $$

CALL GET_PRODUCT_NO_MEASURE_VIEW('2016-07-20 03:37:41', '2016-07-21 03:50:50');
