CREATE OR REPLACE  VIEW PROCESS_N0_VIEW AS
SELECT *
FROM PROCESS_N0
COMMIT;

CREATE OR REPLACE  VIEW PROCESS_N1_VIEW AS

SELECT PROCESS_N1.PROC_N1_ID, PROCESS_N1.PROC_N1_NAME, PROCESS_N1.PROC_N0_ID, PROCESS_N0.PROC_N0_NAME
FROM PROCESS_N1 LEFT JOIN PROCESS_N0 ON PROCESS_N1.PROC_N0_ID = PROCESS_N0.PROC_N0_ID;

COMMIT;

CREATE OR REPLACE  VIEW PROCESS_N2_VIEW AS

SELECT PROCESS_N2.PROC_N2_ID, PROCESS_N2.PROC_N2_NAME, PROCESS_N2.PROC_N1_ID, PROCESS_N1.PROC_N1_NAME
FROM PROCESS_N2 LEFT JOIN PROCESS_N1 ON PROCESS_N2.PROC_N1_ID = PROCESS_N1.PROC_N1_ID;

COMMIT;


CREATE OR REPLACE  VIEW PROCESS_N3_VIEW AS

SELECT PROCESS_N3.PROC_N3_ID, PROCESS_N3.PROC_N3_NAME, PROCESS_N3.PROC_N2_ID, PROCESS_N2.PROC_N2_NAME
FROM PROCESS_N3 LEFT JOIN PROCESS_N2 ON PROCESS_N3.PROC_N2_ID = PROCESS_N2.PROC_N2_ID;

COMMIT;