CREATE OR REPLACE VIEW PRODUCT_DEFECTS_DETAIL AS
SELECT PRODUCT_VIEW.PDT_ID,
		PRODUCT_VIEW.PROC_N0_ID,
		PRODUCT_VIEW.PROC_N0_NAME,
		PRODUCT_VIEW.PDT_NAME,
	   COUNT(*) as 'TOTAL_MEASURES',
	   (COUNT(*) -SUM(PDT_DELIVERY_OPT)) AS 'OP_DEFECTS',
       (COUNT(*) -SUM(MSR_PERTINENCES_OK)) AS 'PERT_DEFECTS',
       ((COUNT(*) -SUM(PDT_DELIVERY_OPT)) + (COUNT(*) -SUM(MSR_PERTINENCES_OK))) AS 'TOTAL_DEFECTS'
       FROM MEASURE_VIEW 
       left join PRODUCT_VIEW on PRODUCT_VIEW.PDT_ID = MEASURE_VIEW.PDT_ID
       group by PDT_NAME;
       

DROP PROCEDURE GET_PRODUCT_DEFECTS_DETAIL;
DELIMITER $$
CREATE PROCEDURE  GET_PRODUCT_DEFECTS_DETAIL
(
	IN dateFrom TIMESTAMP,
    IN dateTo	TIMESTAMP
)
BEGIN
	   
    SELECT PRODUCT_VIEW.PDT_ID,
		PRODUCT_VIEW.PROC_N0_ID,
		PRODUCT_VIEW.PROC_N0_NAME,
		PRODUCT_VIEW.PDT_NAME,
	   COUNT(*) as 'TOTAL_MEASURES',
	   (COUNT(*) -SUM(PDT_DELIVERY_OPT)) AS 'OP_DEFECTS',
       (COUNT(*) -SUM(MSR_PERTINENCES_OK)) AS 'PERT_DEFECTS',
        ((COUNT(*) -SUM(PDT_DELIVERY_OPT)) + (COUNT(*) -SUM(MSR_PERTINENCES_OK))) AS 'TOTAL_DEFECTS'
       FROM MEASURE_VIEW
       left join PRODUCT_VIEW on PRODUCT_VIEW.PDT_ID = MEASURE_VIEW.PDT_ID
       WHERE MSR_DATE >= dateFrom AND MSR_DATE <= dateTo 
       group by PDT_NAME;
      
  
END $$