CREATE OR REPLACE VIEW MEASURE_VIEW AS
SELECT 
	MEASURE_PRODUCT.MSR_ID,
    MEASURE_PRODUCT.PDT_ID,
    PRODUCT.PDT_NAME,
    PRODUCT.PDT_SIGLA,
    MEASURE_PRODUCT.PDT_RAST_CODE,
    MEASURE_PRODUCT.USR_ID,
    USER.USR_NAME,
    MEASURE_PRODUCT.REPROCES_COUNT,
    MEASURE_PRODUCT.AREA_ID,
    AREA.AREA_NAME,
    MEASURE_PRODUCT.DIV_N1_ID,
    DIVISION_N1.DIV_N1_NAME,
    MEASURE_PRODUCT.DIV_N2_ID,
    DIVISION_N2.DIV_N2_NAME,
    MEASURE_PRODUCT.DIV_N3_ID,
    DIVISION_N3.DIV_N3_NAME,
    MEASURE_PRODUCT.PDT_DELIVERY_OPT,
    MEASURE_PRODUCT.MSR_DAYS,
    MEASURE_PRODUCT.MSR_HOUR,
    MEASURE_PRODUCT.MSR_MINUTES,
    MEASURE_PRODUCT.MSR_OK,
    MEASURE_PRODUCT.MSR_PERTINENCES_OK,
    MEASURE_PRODUCT.MSR_DATE
FROM MEASURE_PRODUCT
LEFT JOIN PRODUCT 	ON MEASURE_PRODUCT.PDT_ID  = PRODUCT.PDT_ID
LEFT JOIN USER 		ON MEASURE_PRODUCT.USR_ID  = USER.USR_ID 
LEFT JOIN AREA 		ON MEASURE_PRODUCT.AREA_ID = AREA.AREA_ID
LEFT JOIN DIVISION_N1 		ON MEASURE_PRODUCT.DIV_N1_ID = DIVISION_N1.DIV_N1_ID
LEFT JOIN DIVISION_N2 		ON MEASURE_PRODUCT.DIV_N2_ID = DIVISION_N2.DIV_N2_ID
LEFT JOIN DIVISION_N3 		ON MEASURE_PRODUCT.DIV_N3_ID = DIVISION_N3.DIV_N3_ID;

COMMIT;
