//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVISION_N2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIVISION_N2()
        {
            this.DIVISION_N3 = new HashSet<DIVISION_N3>();
            this.MEASURE_PRODUCT = new HashSet<MEASURE_PRODUCT>();
        }
    
        public int DIV_N2_ID { get; set; }
        public string DIV_N2_NAME { get; set; }
        public int DIV_N1_ID { get; set; }
    
        public virtual DIVISION_N1 DIVISION_N1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIVISION_N3> DIVISION_N3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEASURE_PRODUCT> MEASURE_PRODUCT { get; set; }
    }
}
