//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVISION_N1_VIEW
    {
        public int DIV_N1_ID { get; set; }
        public string DIV_N1_NAME { get; set; }
        public int AREA_ID { get; set; }
        public string AREA_NAME { get; set; }
    }
}
