//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFECTIVITY_VIEW
    {
        public int MSR_ID { get; set; }
        public Nullable<System.DateTime> MSR_DATE { get; set; }
        public string AREA_NAME { get; set; }
        public string PDT_NAME { get; set; }
        public Nullable<decimal> DEFECTS { get; set; }
        public long TOTAL { get; set; }
    }
}
