//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERAL_RESUME_VIEW
    {
        public string PROC_N0_NAME { get; set; }
        public int PDT_ID { get; set; }
        public string PDT_NAME { get; set; }
        public Nullable<decimal> REPROCES_COUNT { get; set; }
        public Nullable<long> MEASURES_COUNT { get; set; }
        public Nullable<long> MEASURES_DEFECTS { get; set; }
        public Nullable<System.DateTime> MSR_DATE { get; set; }
    }
}
