//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASURE_PERTINENCES_VIEW
    {
        public int MSR_ID { get; set; }
        public Nullable<int> PDT_ID { get; set; }
        public string PDT_SIGLA { get; set; }
        public string PDT_RAST_CODE { get; set; }
        public int PERT_ID { get; set; }
        public string PERT_DETAIL { get; set; }
        public Nullable<bool> PERT_VALUE { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public string AREA_NAME { get; set; }
        public Nullable<int> DIV_N1_ID { get; set; }
        public string DIV_N1_NAME { get; set; }
        public Nullable<int> DIV_N2_ID { get; set; }
        public string DIV_N2_NAME { get; set; }
        public Nullable<int> DIV_N3_ID { get; set; }
        public string DIV_N3_NAME { get; set; }
    }
}
