//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERT_MEASURE
    {
        public int MSR_ID { get; set; }
        public int PERT_ID { get; set; }
        public Nullable<bool> PERT_VALUE { get; set; }
    
        public virtual PERTINENCES PERTINENCES { get; set; }
        public virtual MEASURE_PRODUCT MEASURE_PRODUCT { get; set; }
    }
}
