//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERTINENCES_VIEW
    {
        public int PERT_ID { get; set; }
        public string PERT_DETAIL { get; set; }
    }
}
