//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERTINENCES_DEFECTS
    {
        public string PERT_DETAIL { get; set; }
        public int PERT_ID { get; set; }
        public string PROC_N0_NAME { get; set; }
        public string PDT_NAME { get; set; }
        public Nullable<decimal> TOTAL_NO_OK { get; set; }
        public long TOTAL_MEDICIONES { get; set; }
    }
}
