//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS_N1_VIEW
    {
        public int PROC_N1_ID { get; set; }
        public string PROC_N1_NAME { get; set; }
        public int PROC_N0_ID { get; set; }
        public string PROC_N0_NAME { get; set; }
    }
}
