//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_VIEW
    {
        public int PDT_ID { get; set; }
        public string PDT_NAME { get; set; }
        public bool PDT_HASCODE { get; set; }
        public string PDT_SIGLA { get; set; }
        public Nullable<int> PROC_N0_ID { get; set; }
        public string PROC_N0_NAME { get; set; }
        public Nullable<int> PROC_N1_ID { get; set; }
        public string PROC_N1_NAME { get; set; }
        public Nullable<int> PROC_N2_ID { get; set; }
        public string PROC_N2_NAME { get; set; }
        public Nullable<int> PROC_N3_ID { get; set; }
        public string PROC_N3_NAME { get; set; }
        public string PDT_DESC { get; set; }
        public Nullable<int> OP_TYPE_ID { get; set; }
        public string OP_TYPE_NAME { get; set; }
        public Nullable<System.DateTime> PDT_OPORTUNITY_DATE_ACCORDED { get; set; }
        public string PDT_OPORTUNITY_PTO_REF { get; set; }
        public Nullable<int> PDT_OPORTUNITY_DAYS { get; set; }
        public Nullable<int> PDT_OPORTUNITY_HOURS { get; set; }
        public Nullable<int> PDT_OPORTUNITY_MINUTES { get; set; }
        public int GOAL_TYPE_ID { get; set; }
        public string GOAL_TYPE_NAME { get; set; }
        public string GOAL_QUANTITY_MONTH { get; set; }
        public string GOAL_POBLATION { get; set; }
        public Nullable<int> GOAL_CONFIABILITY_INDEX { get; set; }
        public Nullable<int> INDEX_VALUE { get; set; }
        public Nullable<int> GOAL_SAMPLES { get; set; }
    }
}
