//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_ROL_QUERY_VIEW
    {
        public int PDT_ID { get; set; }
        public string PDT_NAME { get; set; }
        public Nullable<int> IS_RELATIONED { get; set; }
        public System.DateTime TIME_COLUMN { get; set; }
    }
}
