//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_DEFECTS_DETAIL
    {
        public Nullable<int> PDT_ID { get; set; }
        public Nullable<int> PROC_N0_ID { get; set; }
        public string PROC_N0_NAME { get; set; }
        public string PDT_NAME { get; set; }
        public long TOTAL_MEASURES { get; set; }
        public Nullable<decimal> OP_DEFECTS { get; set; }
        public Nullable<decimal> PERT_DEFECTS { get; set; }
        public Nullable<decimal> TOTAL_DEFECTS { get; set; }
    }
}
