//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_RELATION_MEASURE_VIEW
    {
        public int MSR_ID { get; set; }
        public string ROL_NAME { get; set; }
        public Nullable<long> TOTAL_MEASURES { get; set; }
    }
}
