//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TYPE_MODULES
    {
        public Nullable<int> TYPE_ID { get; set; }
        public string TYPE_NAME { get; set; }
        public int MODULES_MODULE_ID { get; set; }
        public string MODULE_NAME { get; set; }
        public Nullable<int> MODULE_ID { get; set; }
        public string MODULES_ALIAS { get; set; }
    }
}
