//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS_VIEW
    {
        public int USR_ID { get; set; }
        public int ROL_ID { get; set; }
        public string USR_DOCUMENT { get; set; }
        public string USR_NAME { get; set; }
        public string USR_PU { get; set; }
        public string USR_MAIL { get; set; }
        public string USR_NICK { get; set; }
        public string USR_PASS { get; set; }
        public bool USR_ACTIVE { get; set; }
        public int USR_TYPE { get; set; }
    }
}
